function run_read_data(fname)
% This function determines whether the 'read_data.m' script must be run on the AFINES
% simulation outputs. This code is isolated in an imbedded function to
% prevent the clearing of local variables in the script or function that
% calls this function. The script 'read_data.m' is run on the simulation
% outputs if the data exists, but 'read_data.m' has not been run yet.
% Additionally, 'read_data.m' is run for all simulations that have a zero
% density condition for motors or crosslinkers, due to the unexpected
% format of the variable 'timestep' generated by previous iterations of the
% script
% 
% INPUTS    fname        : String, name of file to be analyzed
% 
% OUTPUTS   NONE

if ~exist('simdata.mat', 'file') && exist('txt_stack', 'file') 
    disp('Need simdata.mat file, will create one now')
    run read_data.m; %Most recent version of the function (IAL: 1/31/17)
elseif ~exist('simdata.mat', 'file') && ~exist('txt_stack', 'file')
    disp('No simdata.mat file')
    disp('No folder txt_stack with actins.txt inside, so can"t make simdata.mat')
    disp('Do it yourself.')
    return
end


end

